# Generated by Django 5.1.7 on 2025-06-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sum_reviews',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='book',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
