# Generated by Django 5.1.7 on 2025-06-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_sum_reviews_book_total_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sum_reviews',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_reviews',
        ),
        migrations.AddField(
            model_name='book',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='review_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
